blueprint:
  name: Motion-activated Light (with Time Restriction)
  description: Turn on a light when motion is detected, with optional active hours.
  domain: automation
  source_url: https://github.com/ondraperny/ha-blueprints/motion_light_time_restricted.yaml
  author: Home Assistant + modified

  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    restrict_to_time:
      name: Restrict to specific hours?
      description: Only run this automation between defined start and end times.
      default: false
      selector:
        boolean:
    start_time:
      name: Active Start Time
      default: "18:00:00"
      selector:
        time: {}
    end_time:
      name: Active End Time
      default: "23:30:00"
      selector:
        time: {}

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

conditions:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not (inputs.restrict_to_time | bool) }}"
      - condition: time
        after: !input start_time
        before: !input end_time

actions:
  - alias: "Turn on the light"
    action: light.turn_on
    target: !input light_target

  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      - trigger: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait

  - alias: "Turn off the light"
    action: light.turn_off
    target: !input light_target
